config/routes.rb
Rails.application.routes.draw do
  root to: "top#index"
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  resources :movies
  resources :materials , only: [:index , :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/material.rb
class Material < ActiveHash::Base
  self.data = [
    {id: 1, name: 'リンク1' , image: "material/templete/material1.png"},
    {id: 2, name: 'リンク2' , image: "material/templete/material2.png"},
    {id: 3, name: 'リンク3' , image: "material/templete/material3.png"},
  ]
end

app/models/movie.rb
class Movie < ApplicationRecord
  attr_accessor :is_confirm
  with_options presence: true do
    validates :title 
    validates :link , length: {is: 11}
    validates :single_point , numericality: {only_integer: true , greater_than_or_equal_to: 1 , less_than_or_equal_to: 5 }
  end
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :nickname
    validates :point
    validates :lank
    validates :experience_point , numericality: {only_integer: true}
  end
  has_many :movies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters , if: :devise_controller?

  private 
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up , keys: [:nickname])
    # binding.pry
  end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  def index
    
  end

  def show
    @material = Material.find(params[:id])
    @is_single_bar_page = true
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :movie_setter
  before_action :find_movie , only: [:show , :edit , :update , :destroy]
  def index
    @movies = Movie.all
  end
  
  def show
    
  end

  def new
    @movie.is_confirm = false
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.valid?
      binding.pry
      if params[:movie][:is_confirm] == "0"
        # まだ確認処理が終わっていない時
        @movie.is_confirm = true
        render :new
      else
        # 確認処理の後の時
        @movie.save();
      end
    else
      # そもそも@movieが保存できないような値だった時
      @movie.is_confirm = false;
      render :new
    end
  end

  def edit
    
  end

  def update
    @movie.update(movie_params)
    binding.pry
  end

  def destroy 
    binding.pry
    @movie.destroy
  end

  private
  def movie_setter
    @movie = Movie.new
  end

  def movie_params
    params.require(:movie).permit(:single_point , :title , :link).merge(user_id: current_user.id)
  end

  def find_movie
    @movie = Movie.find(params[:id])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  def new
    @user = User.new
  end

  def create
    @user = User.new(sign_up_params)
    @user.lank = 1
    @user.experience_point = 0
    @user.point = 0
    binding.pry
    if !@user.valid?
      render "devise/registrations/new" and return
    else
      @user.save
      sign_in(:user, @user)
      redirect_to root_path
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TizerSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if @is_single_bar_page != nil  %>
      <%# single_bar_pageを読み込むという設定になっているとき %>
      <%= stylesheet_link_tag "shared/single_bar_page" , medial: "all" %>
    <% else %>
      <%# 何の設定もされていないとき %>
      <%= stylesheet_link_tag "shared/side_bar_page" , media: "all" %>
    <% end %>
    <%= stylesheet_link_tag "shared/reset" , media: "all" %>
    <%= render partial: "shared/header" %>
    <%= yield %>
  </body>
</html>

app/views/materials/_code_box.html.erb
<div class= "_code_box_parent">
  <div class = "_code_box_head">
    <p class = "_code_box_text"><%= title %></p>
  </div>
  <div class = "_code_box_body">
    <p class = "_code_box_text">
      <pre><code>
      
      </code></pre>
    </p>
  </div>
</div>

app/views/materials/_material_link.html.erb
<%= stylesheet_link_tag "materials/material_link" , media: "all" %>
<div class = "_material_link_parent">
  <p class = "_material_link_title"><%= material.name %></p>
  <%= image_tag material.image , class: "_material_link_image" %>
  <%= link_to "これを使う" , material_path(material.id) , class: "_material_link_button" %>
</div>

app/views/materials/index.html.erb
<div class = "main_content_parent">
  <div class = "top_content">
    <p class = "section_title">素材販売所</p>
  </div>
  <div class = "main_side_parent">
    <div class = "main_content">
      <%= render partial: "material_link" , collection: Material.all , as: "material" %>
    </div>
    <div class = "side_bar">
    
    </div>
  </div>
</div>

app/views/materials/show.html.erb
<%= stylesheet_link_tag "materials/show" , media: "all" %>
<div class = "main_content_parent">
  <div class = "single_bar_page_column">
    <div class = "top_margin"></div>
    <div class = "top_content">
      <p class = "section_title"><%= @material.name %></p>
    </div>

    <div class = "main_content">
      <%= image_tag @material.image , class: "material_image" %>
      <% if params[:id] == "1" %>
        <%= render partial: "materials/templete/1" %>
        <%= render partial: "materials/templete/1_css" %>
      <% elsif params[:id] == "2" %>
        <%= render partial: "materials/templete/2_html" %>
        <%= render partial: "materials/templete/2_css" %>
      <% elsif params[:id] == "3" %>
        <%= render partial: "materials/templete/3" %>

      <% elsif params[:id] == "4" %>

      <% elsif params[:id] == "5" %>

      <% end %>
    </div>
  </div>

  </div>
</div>

app/views/materials/templete/_1.html.erb
<%= stylesheet_link_tag "materials/code_box" , media: "all" %>
<div class= "_code_box_parent">
  <div class = "_code_box_head">
    <p class = "_code_box_head_text">HTML</p>
  </div>
  <div class = "_code_box_body">
    <%# テキストボックス %>
    <p class = "_code_box_text">
      <pre>
        <%# ↓このオブジェクトのIDを検索ボタンにつけられている検索用クラスと同じにする %>
        <code id = "copy_object_1">
&lt%= stylesheet_link_tag "shared/link" , :media =&gt "all" %&gt

&ltdiv class = "_link_links _link_more_than_800px extend_show_object" style = "opacity:0;"&gt
  &lt%= link_to link , class: "_link_a" do %&gt
    &lt% if image != nil %&gt
      &lt%= image_tag image , alter: "#{image}という画像はありません" , class: "_link_image" %&gt
    &lt% else %&gt
      &lt%= image_tag "picture_not_find.png" , class: "_link_image" %&gt
    &lt% end %&gt

    &ltdiv class = "_link_explain"&gt
      &ltp class = "_link_title_text"&gt&lt%= title %&gt&lt/p&gt
      &ltp class = "_link_explain_text"&gt&lt%= explain %&gt&lt/p&gt
      &ltp class = "_link_link_text common_simple_button"&gt &gt&gtページへ移動する&lt/p&gt
    &lt/div&gt
  &lt% end %&gt
&lt/div&gt

&ltdiv class = "_link_links _link_less_than_800px extend_show_object"  style = "opacity:0;"&gt
  &lt%= link_to link , class: "_link_a" do %&gt
    &ltdiv class = "_link_image_and_title"&gt
      &lt% if image != nil %&gt
        &lt%= image_tag image , alter: "#{image}という画像はありません" , class: "_link_image" %&gt
      &lt% else %&gt
        &lt%= image_tag "picture_not_find.png" , class: "_link_image" %&gt
      &lt% end %&gt
      &ltp class = "_link_title_text"&gt&lt%= title %&gt&lt/p&gt
    &lt/div&gt

    &ltdiv class = "_link_explain"&gt
      &ltp class = "_link_explain_text"&gt&lt%= explain %&gt&lt/p&gt
      &ltp class = "_link_link_text common_simple_button"&gt &gt&gtページへ移動する&lt/p&gt
    &lt/div&gt
  &lt% end %&gt
&lt/div&gt
        </code>
      </pre>
    </p>
  </div>
</div>

<%# ↓このオブジェクトのクラスに検索用のクラスを追加する %>
<div class = "_code_box_copy_button _code_box_copy_alert_parent copy_button copy_object_1" id="copy_button">
  コピー
  <%# ↓このIDを、js-copyalert_ + コードが記載してあるcode要素のID と同じにする %>
  <p id="js-copyalert_copy_object_1" class="copy_alert_ _code_box_copy_alert" style="display:none;">コピー完了！</p>
</div>

app/views/materials/templete/_1_css.html.erb
<%= stylesheet_link_tag "materials/code_box" , media: "all" %>
<div class= "_code_box_parent">
  <div class = "_code_box_head">
    <p class = "_code_box_head_text">CSS</p>
  </div>
  <div class = "_code_box_body">
    <%# テキストボックス %>
    <p class = "_code_box_text">
      <pre>
        <%# ↓このオブジェクトのIDを検索ボタンにつけられている検索用クラスと同じにする %>
        <code id = "copy_object_1_css">
._link_links{
  width: 90%;
  padding: 10px;
  border:1px solid black;
  display:flex;
  justify-content: center;
  margin: 25px auto 0px;
  background-color: rgb(252, 255, 240);
  border-radius: 10px;
}

._link_a{
  width:100%;
  display:flex;
  justify-content: center;
  align-items: center;
  text-decoration:none;
  color:black;
  cursor: default;
}

._link_image{
  width:15%;
}

._link_explain{
  width:85%;
  display: flex;
  flex-direction: column;
  align-items: center;
  padding:10px 0;
}

._link_title_text{
  text-align: center;
  font-size:30px;
  margin-bottom: 3px;
}

._link_explain_text{
  padding:0 10px;
  text-align: center;
  max-width:580px;
}

._link_link_text{
  margin-top: 10px;
}



// 800pxより大きい時
  ._link_more_than_800px{
    display:inherit;
  }

  ._link_less_than_800px{
    display:none;
  }


// 800pxより小さいとき
@media (max-width:800px){
  ._link_more_than_800px{
    display:none;
  }

  ._link_less_than_800px{
    display:inherit;
  }

  ._link_a{
    flex-direction: column;
  }

  ._link_title_text{
    margin:auto;
    font-size:20px;
  }

  ._link_image{
    width:auto;
    height:100px;
  }

  ._link_image_and_title {
    margin: auto;
    width: 95%;
    display: flex;
    align-items: center;
    flex-direction: column;
  }

  ._link_explain_text{
    padding:0px;
    text-align: center;
    font-size:15px;
  }

  ._link_explain{
    width:90%;
    padding:5px 0px;
  }
}

@media(max-width:400px){
  ._link_image{
    width:60%;
    height:auto;
  }
}
        </code>
      </pre>
    </p>
  </div>
</div>

<%# ↓このオブジェクトのクラスに検索用のクラスを追加する %>
<div class = "_code_box_copy_button _code_box_copy_alert_parent copy_button copy_object_1_css" id="copy_button">
  コピー

  <%# ↓このIDを、js-copyalert_ + コードが記載してあるcode要素のID と同じにする %>
  <p id="js-copyalert_copy_object_1_css" class="copy_alert _code_box_copy_alert" style="display:none;">コピー完了！</p>
</div>

app/views/materials/templete/_2.html.erb
<%= stylesheet_link_tag "materials/code_box" , media: "all" %>
<div class= "_code_box_parent">
  <div class = "_code_box_head">
    <p class = "_code_box_head_text">HTML</p>
  </div>
  <div class = "_code_box_body">
    <%# テキストボックス %>
    <p class = "_code_box_text">
      <pre>
        <%# ↓このオブジェクトのIDを検索ボタンにつけられている検索用クラスと同じにする %>
        <code id = "copy_object_1">
&lt%= stylesheet_link_tag "shared/link" , :media =&gt "all" %&gt

&ltdiv class = "_link_links _link_more_than_800px extend_show_object" style = "opacity:0;"&gt
  &lt%= link_to link , class: "_link_a" do %&gt
    &lt% if image != nil %&gt
      &lt%= image_tag image , alter: "#{image}という画像はありません" , class: "_link_image" %&gt
    &lt% else %&gt
      &lt%= image_tag "picture_not_find.png" , class: "_link_image" %&gt
    &lt% end %&gt

    &ltdiv class = "_link_explain"&gt
      &ltp class = "_link_title_text"&gt&lt%= title %&gt&lt/p&gt
      &ltp class = "_link_explain_text"&gt&lt%= explain %&gt&lt/p&gt
      &ltp class = "_link_link_text common_simple_button"&gt &gt&gtページへ移動する&lt/p&gt
    &lt/div&gt
  &lt% end %&gt
&lt/div&gt

&ltdiv class = "_link_links _link_less_than_800px extend_show_object"  style = "opacity:0;"&gt
  &lt%= link_to link , class: "_link_a" do %&gt
    &ltdiv class = "_link_image_and_title"&gt
      &lt% if image != nil %&gt
        &lt%= image_tag image , alter: "#{image}という画像はありません" , class: "_link_image" %&gt
      &lt% else %&gt
        &lt%= image_tag "picture_not_find.png" , class: "_link_image" %&gt
      &lt% end %&gt
      &ltp class = "_link_title_text"&gt&lt%= title %&gt&lt/p&gt
    &lt/div&gt

    &ltdiv class = "_link_explain"&gt
      &ltp class = "_link_explain_text"&gt&lt%= explain %&gt&lt/p&gt
      &ltp class = "_link_link_text common_simple_button"&gt &gt&gtページへ移動する&lt/p&gt
    &lt/div&gt
  &lt% end %&gt
&lt/div&gt
        </code>
      </pre>
    </p>
  </div>
</div>

<%# ↓このオブジェクトのクラスに検索用のクラスを追加する %>
<div class = "_code_box_copy_button _code_box_copy_alert_parent copy_button copy_object_1" id="copy_button">
  コピー
  <%# ↓このIDを、js-copyalert_ + コードが記載してあるcode要素のID と同じにする %>
  <p id="js-copyalert_copy_object_1" class="copy_alert_ _code_box_copy_alert" style="display:none;">コピー完了！</p>
</div>

app/views/materials/templete/_2_css.html.erb
<%= stylesheet_link_tag "materials/code_box" , media: "all" %>
<div class= "_code_box_parent">
  <div class = "_code_box_head">
    <p class = "_code_box_head_text">CSS</p>
  </div>
  <div class = "_code_box_body">
    <%# テキストボックス %>
    <p class = "_code_box_text">
      <pre>
        <%# ↓このオブジェクトのIDを検索ボタンにつけられている検索用クラスと同じにする %>
        <code id = "copy_object_1_css">
._link_links{
  width: 90%;
  padding: 10px;
  border:1px solid black;
  display:flex;
  justify-content: center;
  margin: 25px auto 0px;
  background-color: rgb(252, 255, 240);
  border-radius: 10px;
}

._link_a{
  width:100%;
  display:flex;
  justify-content: center;
  align-items: center;
  text-decoration:none;
  color:black;
  cursor: default;
}

._link_image{
  width:15%;
}

._link_explain{
  width:85%;
  display: flex;
  flex-direction: column;
  align-items: center;
  padding:10px 0;
}

._link_title_text{
  text-align: center;
  font-size:30px;
  margin-bottom: 3px;
}

._link_explain_text{
  padding:0 10px;
  text-align: center;
  max-width:580px;
}

._link_link_text{
  margin-top: 10px;
}



// 800pxより大きい時
  ._link_more_than_800px{
    display:inherit;
  }

  ._link_less_than_800px{
    display:none;
  }


// 800pxより小さいとき
@media (max-width:800px){
  ._link_more_than_800px{
    display:none;
  }

  ._link_less_than_800px{
    display:inherit;
  }

  ._link_a{
    flex-direction: column;
  }

  ._link_title_text{
    margin:auto;
    font-size:20px;
  }

  ._link_image{
    width:auto;
    height:100px;
  }

  ._link_image_and_title {
    margin: auto;
    width: 95%;
    display: flex;
    align-items: center;
    flex-direction: column;
  }

  ._link_explain_text{
    padding:0px;
    text-align: center;
    font-size:15px;
  }

  ._link_explain{
    width:90%;
    padding:5px 0px;
  }
}

@media(max-width:400px){
  ._link_image{
    width:60%;
    height:auto;
  }
}
        </code>
      </pre>
    </p>
  </div>
</div>

<%# ↓このオブジェクトのクラスに検索用のクラスを追加する %>
<div class = "_code_box_copy_button _code_box_copy_alert_parent copy_button copy_object_1_css" id="copy_button">
  コピー

  <%# ↓このIDを、js-copyalert_ + コードが記載してあるcode要素のID と同じにする %>
  <p id="js-copyalert_copy_object_1_css" class="copy_alert _code_box_copy_alert" style="display:none;">コピー完了！</p>
</div>

app/views/materials/templete/_3.html.erb
<%= stylesheet_link_tag "materials/code_box" , media: "all" %>
<div class= "_code_box_parent">
  <div class = "_code_box_head">
    <p class = "_code_box_head_text">HTML</p>
  </div>
  <div class = "_code_box_body">
    <%# テキストボックス %>
    <p class = "_code_box_text">
      <pre>
        <%# ↓このオブジェクトのIDを検索ボタンにつけられている検索用クラスと同じにする %>
        <code id = "copy_object_1">
&ltp class = "open_sort_button"&gt並び替えを使用する&lt/p&gt
        </code>
      </pre>
    </p>
  </div>
</div>



<%# ↓このオブジェクトのクラスに検索用のクラスを追加する %>
<div class = "_code_box_copy_button _code_box_copy_alert_parent copy_button copy_object_1" id="copy_button">
  コピー
  <%# ↓このIDを、js-copyalert_ + コードが記載してあるcode要素のID と同じにする %>
  <p id="js-copyalert_copy_object_1" class="copy_alert_ _code_box_copy_alert" style="display:none;">コピー完了！</p>
</div>

<div class= "_code_box_parent">
  <div class = "_code_box_head">
    <p class = "_code_box_head_text">CSS</p>
  </div>
  <div class = "_code_box_body">
    <%# テキストボックス %>
    <p class = "_code_box_text">
      <pre>
        <%# ↓このオブジェクトのIDを検索ボタンにつけられている検索用クラスと同じにする %>
        <code id = "copy_object_1">
.open_sort_button {
  display: block;
  text-align: center;
  background: linear-gradient(to right bottom , #1919ff , #000089);
  width: 300px;
  line-height: 40px;
  border-radius: 10px;
}
        </code>
      </pre>
    </p>
  </div>
</div>

<%# ↓このオブジェクトのクラスに検索用のクラスを追加する %>
<div class = "_code_box_copy_button _code_box_copy_alert_parent copy_button copy_object_1" id="copy_button">
  コピー
  <%# ↓このIDを、js-copyalert_ + コードが記載してあるcode要素のID と同じにする %>
  <p id="js-copyalert_copy_object_1" class="copy_alert_ _code_box_copy_alert" style="display:none;">コピー完了！</p>
</div>

app/views/movies/create.html.erb
作成完了

app/views/movies/destroy.html.erb
削除完了

app/views/movies/index.html.erb
動画トップページ
<%= link_to "新規投稿" , new_movie_path %>

<% @movies.each do |movie| %>
  <%= link_to movie.title , movie_path(movie) %>
<% end %>

app/views/movies/new.html.erb
動画投稿
<% if @movie.is_confirm == false %>
  確認前。
  <%= form_with model: @movie , url: movies_path(@movie) , local: true do |f| %>
    <%= render partial: "shared/error_messages" , locals: {model: @movie} %>
    <%= f.label :title ,  "タイトル" %>
    <%= f.text_field :title , autofocus: true %>

    <%= f.label :link ,  "リンク" %>
    <%= f.text_field :link %>

    <%= f.label :single_point ,  "ポイント" %>
    <%= f.number_field :single_point %>

    <%= f.check_box :is_confirm , readonly: "readonly" %>後で見えないようにする
    <%= f.submit "作成" %>
  <% end %>
<% else %>
  確認をします。きちんと動画が表示されていることを確認してください。
  <iframe width="950" height="534" src="https://www.youtube.com/embed/<%= @movie.link%>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  <%= image_tag "https://img.youtube.com/vi/#{@movie.link}/maxresdefault.jpg" , class: "_reccomend_movie_image" %>
  <%= form_with model: @movie , url: movies_path(@movie) , local: true do |f| %>
    <%= render partial: "shared/error_messages" , locals: {model: @movie} %>
    <%= f.label :title ,  "タイトル" %>
    <%= f.text_field :title , readonly: "readonly" %>

    <%= f.label :link ,  "リンク" , readonly: "readonly" %>
    <%= f.text_field :link %>

    <%= f.label :single_point ,  "ポイント" , readonly: "readonly" %>
    <%= f.number_field :single_point %>

    <%= f.check_box :is_confirm , readonly: "readonly" %>後で見えないようにする
    <%= f.submit "作成" %>
  <% end %>
<% end %>

app/views/movies/update.html.erb
編集完了

app/views/top/index.html.erb
<div class = "main_content_parent">
  <div class = "top_content">
    <p class = "section_title">トップページ</p>
  </div>
  <div class = "main_side_parent">
    <div class = "main_content">
      <% if user_signed_in? %>
        <%= link_to "ログアウト" , destroy_user_session_path , method: :delete %>
      <% else %>
        <%= link_to "新規登録" , new_user_registration_path %>
        <%= link_to "ログイン" , new_user_session_path %>
      <% end %>
      <%= link_to "動画一覧へ" , movies_path %>
      <%= link_to "部分テンプレート販売所へ" , materials_path %>
    </div>
    <div class = "side_bar">
    
    </div>
  </div>
</div>